# Generated by Django 5.1.15 on 2026-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('soutien', 'Soutien Participatif (Ministres/Hauts Cadres)'), ('expert_ca', 'Expert - Conseil d’Administration PCC'), ('expert_hca', 'Expert - Hors Conseil d’Administration PCC'), ('talent', 'Talent & Compétence (Local)'), ('diaspora', 'Talent & Compétence (Diaspora)'), ('admin', 'Administrateur Système')], default='talent', max_length=20, verbose_name='Segmentation'),
        ),
    ]
