BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB BBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Modifier mon profil')  X XXXBBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX XXXX XXXXXXX
    XXXX XXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Retour au profil') 
        XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                 gettext(u'Paramètres du Profil') 
            XXXXX
        XXXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX
            BBBBBBBBBB

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                XXXX XXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Biographie professionnelle') XXXXXXXX
                     _("Parlez-nous de votre parcours et de vos ambitions...") 
                    BB BBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Intitulé du poste actuel') XXXXXXXX
                    BBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Localisation') XXXXXXXX
                     _("Ville, Pays") 
                    BB BBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u"Années d'expérience") XXXXXXXX
                    BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Disponibilité') XXXXXXXX
                     _("Immédiate, 1 mois...") 
                    BB BBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Visibilité publique') XXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Votre profil sera visible par les recruteurs et institutions.') XXXX
                    XXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBB
                        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Annuler') XXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                     gettext(u'Enregistrer les modifications') 
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXXX
BBBBBBBB
