BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFF X XXXBBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX XXXX XXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXX X XXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
            BB BBBB BB BBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX gettext(u'Modifier mon profil') XXXXXXX
                XXXX
            BBBBB
        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Profil Vérifié') XX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXX
                        BBBBB
                    XXXXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXX _("Profession non spécifiée") XXXX
                    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  _("Bénin") XXXXXXX
                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX   gettext(u"ans d'expérience") XXXXXXX
                        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  _("Disponible") XXXXXXX
                    XXXXXX
                XXXXXX
                BB BBBB BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXX XXXXXX
                    XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                         gettext(u'Contacter') 
                    XXXXXXXXX
                XXXXXX
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                XXXX XXXX XXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXX XXX
                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX
                             gettext(u'Biographie & Objectifs') 
                        XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                             _("Aucune biographie disponible pour le moment.") 
                        XXXX
                    XXXXXXXXXX

                    XXXX XXXXXXXXXX XXX
                    XXXXXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXX
                             gettext(u'Expériences & Projets') 
                        XXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXX XXXXX XXXXXXXXXX
                                XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXX
                                    XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX X FFFFFFFF X BB BBBBBBBBBBBBBB gettext(u'Présent') BBBBFFFFFFFFBBBBBXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                            BBBBB
                                XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX gettext(u'Aucune expérience renseignée.') XXXX
                            BBBBBB
                        XXXXXX
                    XXXXXXXXXX

                    XXXX XXXXXXXXX XXX
                    XXXXXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                             gettext(u'Formation Académique') 
                        XXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                            BBB BBB BB BBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                                XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX X FFFFFFFFXXXX
                            XXXXXX
                            BBBBB
                                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Aucun diplôme renseigné.') XXXX
                            BBBBBB
                        XXXXXX
                    XXXXXXXXXX
                XXXXXX

                XXXX XXXXX XXXXXX XXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXX XXX
                    XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                             gettext(u'Expertise & Compétences') 
                        XXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
                            BBB BBBBB BB BBBBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                        
                                    XXXXXXX
                                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        
                                    XXXXXX
                                XXXXXX
                            BBBBB
                                XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX gettext(u'Aucune compétence listée.') XXXX
                            BBBBBB
                        XXXXXX
                    XXXXXXXXXX

                    XXXX XXXXXXXXX XXX
                    XXXXXXXX XXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                             gettext(u'Documents vérifiés') 
                        XXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            BBB BBB BB BBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBXXXXXXXXXXXBBBBXXXXXXXXXXXBBBBB XXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBB
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX gettext(u'Document Vérifié') XXXXXX
                                BBBBB
                            XXXXXX
                            BBBBB
                                XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX gettext(u'Aucun document partagé.') XXXX
                            BBBBBB
                        XXXXXX
                    XXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXX
BBBBBBBB
