BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Explorer les Talents')  X XXXBBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX XXXX XXXX XXXXXXXXXX
    XXXX XXXXXX X XXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXX gettext(u'Explorer les talents') XXXXX
        
        XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Nom, rôle, biographie...') XXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXX gettext(u'Ville / Pays') XXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXX gettext(u'Compétence') XXX
                XXXXXX

                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX
                     gettext(u'Actualiser') 
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Talents disponibles')  
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
        XXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Trier par')  XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Pertinence') XXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Nouveauté') XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXX XXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        BBB BBBBBB BB BBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXX XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBB B B gettext(u'Expert') BBBB gettext(u'Senior') BBBBB
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  _("Bénin") 
                        XXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXX
                 _("Consultant Indépendant") 
            XXXX

            XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                    
                XXXXXXX
                BBBBBB
            XXXXXX

            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                 gettext(u'Voir le profil') 
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Aucun talent trouvé') XXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX gettext(u"Essayez d'ajuster vos filtres de recherche.") XXXX
        XXXXXX
        BBBBBB
    XXXXXX

    XXXX XXXXXXXXXX XXX
    BB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX
        BBBBB
        
        XXXX XXXXXXXXXXX XXXXXXX
            BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBB BB B
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBBB
                    XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
            BBBBBB
        XXXXXX

        BB BBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXBB BBBBBBBBBBBBBXXXBBBBBX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX
        BBBBB
    XXXXXX
    BBBBB
XXXXXXX
BBBBBBBB
