# Generated by Django 5.1.15 on 2026-03-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_citizenprofile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='charter_signed',
            field=models.BooleanField(default=False, verbose_name="Charte d'éthique signée"),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Profil Validé'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='citizen_photos/'),
        ),
    ]
