# Generated by Django 5.1.15 on 2026-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_citizenprofile_charter_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('alibori', 'Alibori'), ('atacora', 'Atacora'), ('atlantique', 'Atlantique'), ('borgou', 'Borgou'), ('collines', 'Collines'), ('couffo', 'Couffo'), ('donga', 'Donga'), ('littoral', 'Littoral'), ('mono', 'Mono'), ('oueme', 'Ouémé'), ('plateau', 'Plateau'), ('zou', 'Zou')], max_length=50),
        ),
    ]
