# Generated by Django 5.1.15 on 2026-03-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_alter_citizenprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_citizens', to='citizens.category', verbose_name="Domaines d'intérêt"),
        ),
    ]
