BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB BBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Connexion')  X XXXBBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                     gettext(u"Retour à l'accueil") 
                XXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Bon retour !') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Connectez-vous à votre espace PCC') XXXX
                XXXXXX
                
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                                
                            BBBBBB
                        XXXXXX
                    BBBBB

                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX gettext(u"Nom d'utilisateur") XXXXXXXX
                        BBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBB BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
                        BB BBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        BBBBB
                    XXXXXX

                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX gettext(u'Mot de passe') XXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Oublié ?') XXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                            BBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBB BBBB BBBBB BBBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                        BB BBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        BBBBB
                    XXXXXX

                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Se connecter') 
                    XXXXXXXXX
                    
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                XXXXXXX
                
                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX gettext(u'Ou') XXXXXXX
                    XXXXXX
                XXXXXX
                
                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                     gettext(u'Pas encore de compte ?')  
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX gettext(u"S'inscrire") XXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB
