# Generated by Django 5.1.15 on 2026-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_event_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(help_text='Lien YouTube complet')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
            },
        ),
    ]
