BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBBBB
XXXX XXXX XXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXX XXX XXXXX
                    XXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX
                 gettext(u'Plateforme Citoyenne de Compétences') 
            XXXXXX
            XXX
                XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                 gettext(u'Propulsez votre')  XXX XX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'expertise') XXXXXXX  gettext(u'béninoise') 
            XXXXX
            XX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX
                XX XXXXX XXX XXXXXXX XXXXXXXX XXX XXXXXXX XXXX XXXXX XXXXXXXX XX XXXXXX XXXXXXXXXXXXXX XXX XXXXXXX
                XXXXXXXXXXXX XX XX XXXXXXXX XX
            XXXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXX
                    XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
                     gettext(u"S'inscrire gratuitement") 
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX
                    XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                     gettext(u'Découvrir les talents') 
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXX
                    XXXXXXXXX XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXX
                XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

            XXXX
                XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                            XXXXXXX XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXX XXX XXX XXXXXXXXX
                            XXXXXXXXXXX XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX

XXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX
                    XXXXXXX XXXXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Dernières Opportunités Nationales') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX XXX XXXXXX X XXXXXXX XXXXXXXXXXXX XX
                    XXXXXXXXXXXX XX XXX XXXXXXXXXXXXXX XXXXXX
            XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXX
                 gettext(u'Voir tout') 
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
            XXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXX
                XXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX
                    
                XXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        
                    XXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBX
                        XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX
                XXXXXX
            XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX gettext(u'Chargement des opportunités...') 
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX
                XXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXX gettext(u"Portraits d'Experts") XXXXX
            XXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
            BBB BBBBBB BB BBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXX
                XXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX
                             _("Consultant") XXXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
                            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX
                                XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXXXXXX XXXXXXXXX
                            BBBBBB
                        XXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
                            XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXX
                             gettext(u'Profil complet') 
                            XX XXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXX XXXX XXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u"L'Actualité du Talent") XXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX
                XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXX
                 gettext(u"Toute l'actualité") 
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
            BBB BBBB BB BBBBBBBBBBBB
            XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXX
                        XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                    BBBB
                    XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                    BBBBB
                    XXXX
                        XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX
                            XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
                             gettext(u"Lire l'article") 
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXX
                    XXXXXX
                XXXXXX
                XXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                        XXXXX
                            XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFF F FFXXXXXXX
                    XXXXXX
                    XXX
                        XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX
                XXXXXX
            XXXXXXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXX XX XXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                 gettext(u"Prêt à contribuer à l'essor")  XXX XX  gettext(u'du Bénin ?') 
            XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXX
                    XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Rejoindre maintenant') 
                XXXX
                XX XXXXXXXX
                    XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                     gettext(u'En savoir plus') 
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB