BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Opportunités')  X XXXBBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX XXXX XXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXX gettext(u'Dernières Opportunités') XXXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Découvrez les projets stratégiques et appels à expertise des institutions du Bénin.') XXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                     gettext(u'Filtrer') 
                XXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Statut du projet') XXXX
                        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Ouvert') XXXXXXX
                            XXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'À venir') XXXXXXX
                            XXXXXXXX
                        XXXXXX
                    XXXXXX

                    XXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                         gettext(u'Appliquer les filtres') 
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            BBB BBBBBBBBBBB BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX
                        BBBB
                            XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
                            XXXXX
                                XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX _("Bénin") XXXXXXX
                                XXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                                
                            XXXXXXX
                        XXXXXX
                        
                        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                            
                        XXXX

                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Clôture')  X FFFFFFF F FFXXXXXXX
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX   gettext(u'candidats') XXXXXXX
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                             gettext(u'Consulter & Postuler') 
                        XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Aucune opportunité disponible') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX gettext(u'Revenez bientôt pour de nouveaux projets.') XXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXX
BBBBBBBB
