BBBB BBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXX X XXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXBBBBBBBBXXXXXXXX
    
    XXXX XXXXXXX X XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X X
            XXXXXXXXX XXXXXXXX
            XXXXXX X
                XXXXXXX X
                    XXXXXXX X
                        XXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXX
                    XX
                    XXXXXXXXXXX X
                        XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                    XX
                    XXXXXXXXXXXXX X
                        XXXXXXXXXX XXXXXXXXXX
                        XXXXX XXXXXXXXX
                        XXXXX XXXXXXXXXX
                        XXXXXXX XXXXXXXX
                    XX
                XX
            XX
        X
    XXXXXXXXX
    XXXXXXX
        XXXX X XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXX XXXX XXXXXX XX XXXXXX XXX X
    XXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXX

    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
            
            XXXX XXXXXXX XXX XXX
            XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Accueil') XXXX
                XX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Talents') XXXX
                XX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Opportunités') XXXX
                XX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB BBB BBBBBB BB BBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'Blog') XXXX
                XX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB BBB BBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX gettext(u'Événements') XXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXX
                
                XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX gettext(u'Mon Espace') XXXX
                            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Déconnexion') XXXXXXXXX
                            XXXXXXX
                        XXXXXX
                    BBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Connexion') XXXX
                        XX XXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Rejoindre') XXXX
                    BBBBB
                XXXXXX
                
                XXXX XXXXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                            BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                            BBB BBBB BB BBBBBBBBB
                                XXXXXXX XXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX
                                    FFFFF
                                XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXXX
                XXXXXX

                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXX XXXX XXXXXXXX XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Navigation') XXXX
                    XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                         gettext(u'Accueil') 
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX
                         gettext(u'Talents') 
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                         gettext(u'Opportunités') 
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB BBB BBBBBB BB BBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                         gettext(u'Blog') 
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB BBB BBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX
                         gettext(u'Événements') 
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX
                XXXXXX

                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                         XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Déconnexion') 
                                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXXX
                    BBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Connexion') XXXX
                        XX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Rejoindre') XXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXX
        BB BBBBBBBB
            XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
                BBB BBBBBBB BB BBBBBBBB
                    XXXX XXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXXBBBB BBBBBBBBBBBB BB BBBBBBBXXXXXXXXXX XXXXXXXXXXXXBBBBXXXXXXXXXXX XXXXXXXXXXXXXBBBBB XXXXXX
                        
                    XXXXXX
                BBBBBB
            XXXXXX
        BBBBB
        
        BBBBB BBBBBBBBBBBBBBB
    XXXXXXX

    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX
                         gettext(u'La Plate-Forme Citoyenne des Compétences est une initiative citoyenne un Think Tank Citoyen pour valoriser les talents béninois.') 
                    XXXX
                    XXXX XXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXX
                    XXXXXX
                XXXXXX
                XXXXX
                    XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Plateforme') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Comment ça marche') XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Talents à la une') XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u"Offres d'emploi") XXXXXXXXX
                    XXXXX
                XXXXXX
                XXXXX
                    XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Support') XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Aide & FAQ') XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Contact') XXXXXXXXX
                    XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Newsletter') XXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX gettext(u'Restez informé des dernières opportunités nationales.') XXXX
                    XXXX XXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XXXX XXXX XXXX  gettext(u'Tous droits réservés.') XXXX
                XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Confidentialité') XXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Cookies') XXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX gettext(u'République du Bénin') XXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX

    XXXX XXXXXX XXXXXXX XXX
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
                XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXX XXXXXX XXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXX
                X
            XXX

            XXXXXXXX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXX
            X

            XX XXXXX XX XXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXX
                    X
                X
            XXX
        XXX
    XXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX
